services:
  mongodb:
    container_name: mongo.db
    image: mongo
    ports:
        - '27017:27017'
    volumes:
        - mongo-data:/var/lib/mongodb/data
    networks:
        - exam
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin@12345
  sqlserver:
    container_name: sqlserver.db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - '1433:1433'
    volumes:
        - sqlserver_data:/var/opt/mssql
    networks:
        - exam
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Admin@12345
  identity.api:
    container_name: identity.api
    build:
      context: .
      dockerfile: src/Identity/Identity.API/Dockerfile
    ports:
        - '5001:8080'
    networks:
        - exam
    restart: always
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__IdentitySqlConnection: "Server=sqlserver.db,1433;Database=ExamIdentity;User Id=sa;Password=Admin@12345;TrustServerCertificate=True;"

networks:
    exam:
        driver: bridge
volumes:
    mongo-data:
    sqlserver_data:
