namespace Exam.Contracts;

public record ExamDto(
    string Id,
    string Name,
    string ShortDesc,
    string Content,
    TimeSpan Duration,
    Level Level,
    DateTime DateCreated,
    string OwnerUserId,
    decimal MinimumPassingScore,
    bool IsTimeRestricted,
    string CategoryId,
    string CategoryName,
    ExamStatus Status,
    QuestionSelectionMode QuestionSelectionMode,
    string PoolCategoryId,
    int PoolQuestionCount,
    DateTime? AvailableFrom,
    DateTime? AvailableTo,
    decimal NegativeMarkingRatio,
    IReadOnlyCollection<string> QuestionIds,
    int NumberOfQuestions,
    IReadOnlyCollection<string> AssignedClassIds,
    bool IsPublic,
    int? MaxAttempts);
